### ISSUE TITLE
Sveltekit

### ISSUE THREAD

**Issue by lovelindhoni** [probablykasper/tauri-svelte-template#2]
Buddy, please do an template for sveltekit with tauri with the tauri actions for cross platform compliation

**Comment by kasper9n** [comment]
I wouldn't really recommend using SvelteKit with Tauri because you'll need to use ugly workarounds to use the Tauri api due to SvelteKit running your code in SSR

I do have a SvelteKit template without Tauri if you need it https://github.com/probablykasper/sveltekit-template

**Comment by edjw** [comment]
The Tauri docs do now use SvelteKit over Svelte for their quickstart. SvelteKit has added the SSG mode which given your comment above is maybe the thing you needed?

https://tauri.app/v1/guides/getting-started/setup/sveltekit

**Comment by kasper9n** [comment]
The `ssr` option might make it possible now, yeah. Not sure I'll make a template for it, probably only if I need it at some point

**Comment by kasper9n** [comment]
I converted this repo to be a SvelteKit template
