### ISSUE TITLE
[ERROR]  faild load resuore "res/icon.ico"

### ISSUE THREAD

**Issue by Cloud-11** [probablykasper/tauri-svelte-template#3]
[run] : pnpm dev 

[error info]:

Caused by:
  process didn't exit successfully: `X:\tauri-svelte-template\src-tauri\target\debug\build\tauri-template-9706c895f569b435\build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-env-changed=TAURI_CONFIG
  cargo:rerun-if-changed=tauri.conf.json
  cargo:rustc-cfg=dev

  --- stderr
  thread 'main' panicked at 'Error: `res/icon.ico` not found; required for generating a Windows Resource file during tauri-build', X:\rust\.cargo\registry\src\mirrors.ustc.edu.cn-61ef6e0cd06fb9b8\tauri-build-1.0.2\src\lib.rs:176:9
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...

OS : windows11
NODE:  v16.5.0
rustup : 1.24.3
rustc : 1.62.0

Tried many times still so, hope to get help

**Comment by kasper9n** [comment]
Does it happen with npm too?

The CI works fine for Windows, so not sure what would be causing this

**Comment by kasper9n** [comment]
And you do have `src-tauri/icons/icon.ico` right?

**Comment by Cloud-11** [comment]
Sorry, it was my environment. I re-installed Rust and it was running successfully.
