### ISSUE TITLE
Typescript not working when importing svelte files

### ISSUE THREAD

**Issue by pythonicode** [probablykasper/tauri-svelte-template#4]
`Cannot find module '@/components/core/Copy.svelte' or its corresponding type declarations.`
`Cannot find module '@/components/core/Tooltip.svelte' or its corresponding type declarations.`

in the following file
```html
<script lang="ts">
  import { open } from '@tauri-apps/api/dialog'
  import ArrowLeft from 'svelte-material-icons/ArrowLeft.svelte'
  import Eye from 'svelte-material-icons/Eye.svelte'
  import EyeOff from 'svelte-material-icons/EyeOff.svelte'
  import { Link } from 'svelte-navigator'
  import Copy from '@/components/core/Copy.svelte'
  import Tooltip from '@/components/core/Tooltip.svelte'

  let directory = 'C:\\Users\\AppData\\Roaming\\Discharge\\Something'
  let uid = '1ed28dcb-eaa7-4bbd-879d-e979bde8cd57'
  let password = ''
  let confirm = ''
  let visible = false
</script>
```

Strange because it seems to work with the other *.svelte files

**Comment by kasper9n** [comment]
I'm guessing that `@/components` isn't something it knows where to find. Is that something it's supposed to know?

**Comment by pythonicode** [comment]
Yeah my mistake. I didn't update tsconfig with the type aliasing.
