### ISSUE TITLE
Long lags in the layout painting

### ISSUE THREAD

**Issue by mantzaris** [probablykasper/tauri-svelte-template#6]
I ran the template after installation and followed the steps in the readme and got the main window to show with the counter iteration working as expected. The HMR also works, but there is a large lag when resizing the window. The layout painting has a lag of 1-4 seconds, so that if the window is expanded the previous size remains as a subpart till it fills the new larger width. Is this expected? I have been trying to see if it is something on my end but I can't point it out. I tried some modifications and the scroll bar also takes a very long time to adjust the view.

**Comment by kasper9n** [comment]
Try updating all the JS & Rust dependencies, and also check if it's fine after building the app. This is really just a basic template, nothing here that should have an impact, so I don't have any other suggestions

**Comment by mantzaris** [comment]
after building the resizing delay (on Ubuntu) still exists although the styling and counter work fine
